# Generated by Django 5.0 on 2026-05-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionparticipant',
            name='invite_status',
            field=models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='invited', max_length=20),
        ),
    ]
