# Generated by Django 5.0 on 2026-05-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0002_sessionparticipant_invite_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='video_room_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
