# Generated by Django 5.0 on 2026-05-29 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0003_studysession_video_room_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='actual_duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='parent_session',
            field=models.ForeignKey(blank=True, db_column='parent_session_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_instances', to='study_sessions.studysession'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='recurrence',
            field=models.CharField(blank=True, default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='studysession',
            name='recurrence_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studysession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
